package movie_organizer.rest_service.web.model;

public enum MovieRatingEnum {
	G_GENERAL_AUDIENCES, PG_PARENTAL_GUIDANCE_SUGGESTED,
	PG_13_PARENTS_STRONGLY_CAUTIONED, R_RESTRICTED,
	NC_17_CLEARLY_ADULT, UNRATED
}
